#ifndef NIGHT_TRANSIT_RESOURCE_H
#define NIGHT_TRANSIT_RESOURCE_H

#define IDD_NIGHT_TRANSIT_CONFIG 1301

#define IDC_NIGHT_TRANSIT_INFO 13001
#define IDC_NIGHT_TRANSIT_PRESET 13002
#define IDC_NIGHT_TRANSIT_THEME 13003
#define IDC_NIGHT_TRANSIT_SCENE 13004
#define IDC_NIGHT_TRANSIT_SPEED 13005
#define IDC_NIGHT_TRANSIT_LIGHTS 13006
#define IDC_NIGHT_TRANSIT_DETERMINISTIC 13007
#define IDC_NIGHT_TRANSIT_DIAGNOSTICS 13008
#define IDC_NIGHT_TRANSIT_DEFAULTS 13009

#endif /* NIGHT_TRANSIT_RESOURCE_H */
