#ifndef FRACTAL_ATLAS_RESOURCE_H
#define FRACTAL_ATLAS_RESOURCE_H

#define IDD_FRACTAL_ATLAS_CONFIG 1801

#define IDC_FRACTAL_ATLAS_INFO 18001
#define IDC_FRACTAL_ATLAS_PRESET 18002
#define IDC_FRACTAL_ATLAS_THEME 18003
#define IDC_FRACTAL_ATLAS_MODE 18004
#define IDC_FRACTAL_ATLAS_SPEED 18005
#define IDC_FRACTAL_ATLAS_REFINEMENT 18006
#define IDC_FRACTAL_ATLAS_DETERMINISTIC 18007
#define IDC_FRACTAL_ATLAS_DIAGNOSTICS 18008
#define IDC_FRACTAL_ATLAS_DEFAULTS 18009

#endif /* FRACTAL_ATLAS_RESOURCE_H */
