#ifndef SIGNAL_LAB_RESOURCE_H
#define SIGNAL_LAB_RESOURCE_H

#define IDD_SIGNAL_LAB_CONFIG 901

#define IDC_SIGNAL_LAB_INFO 9001
#define IDC_SIGNAL_LAB_PRESET 9002
#define IDC_SIGNAL_LAB_THEME 9003
#define IDC_SIGNAL_LAB_LAYOUT 9004
#define IDC_SIGNAL_LAB_ACTIVITY 9005
#define IDC_SIGNAL_LAB_OVERLAY 9006
#define IDC_SIGNAL_LAB_DETERMINISTIC 9007
#define IDC_SIGNAL_LAB_DIAGNOSTICS 9008
#define IDC_SIGNAL_LAB_DEFAULTS 9009

#endif /* SIGNAL_LAB_RESOURCE_H */
