#ifndef MECHANICAL_DREAMS_RESOURCE_H
#define MECHANICAL_DREAMS_RESOURCE_H

#define IDD_MECHANICAL_DREAMS_CONFIG 1001

#define IDC_MECHANICAL_DREAMS_INFO 10001
#define IDC_MECHANICAL_DREAMS_PRESET 10002
#define IDC_MECHANICAL_DREAMS_THEME 10003
#define IDC_MECHANICAL_DREAMS_SCENE 10004
#define IDC_MECHANICAL_DREAMS_SPEED 10005
#define IDC_MECHANICAL_DREAMS_DENSITY 10006
#define IDC_MECHANICAL_DREAMS_DETERMINISTIC 10007
#define IDC_MECHANICAL_DREAMS_DIAGNOSTICS 10008
#define IDC_MECHANICAL_DREAMS_DEFAULTS 10009

#endif /* MECHANICAL_DREAMS_RESOURCE_H */
