#ifndef RETRO_EXPLORER_RESOURCE_H
#define RETRO_EXPLORER_RESOURCE_H

#define IDD_RETRO_EXPLORER_CONFIG 1501

#define IDC_RETRO_EXPLORER_INFO 15001
#define IDC_RETRO_EXPLORER_PRESET 15002
#define IDC_RETRO_EXPLORER_THEME 15003
#define IDC_RETRO_EXPLORER_SCENE 15004
#define IDC_RETRO_EXPLORER_SPEED 15005
#define IDC_RETRO_EXPLORER_DETAIL_MODE 15006
#define IDC_RETRO_EXPLORER_DETERMINISTIC 15007
#define IDC_RETRO_EXPLORER_DIAGNOSTICS 15008
#define IDC_RETRO_EXPLORER_DEFAULTS 15009

#endif /* RETRO_EXPLORER_RESOURCE_H */
