#ifndef VECTOR_WORLDS_RESOURCE_H
#define VECTOR_WORLDS_RESOURCE_H

#define IDD_VECTOR_WORLDS_CONFIG 1601

#define IDC_VECTOR_WORLDS_INFO 16001
#define IDC_VECTOR_WORLDS_PRESET 16002
#define IDC_VECTOR_WORLDS_THEME 16003
#define IDC_VECTOR_WORLDS_SCENE 16004
#define IDC_VECTOR_WORLDS_SPEED 16005
#define IDC_VECTOR_WORLDS_DETAIL 16006
#define IDC_VECTOR_WORLDS_DETERMINISTIC 16007
#define IDC_VECTOR_WORLDS_DIAGNOSTICS 16008
#define IDC_VECTOR_WORLDS_DEFAULTS 16009

#endif /* VECTOR_WORLDS_RESOURCE_H */
