#ifndef VECTOR_WORLDS_RESOURCE_H
#define VECTOR_WORLDS_RESOURCE_H

#define IDD_VECTOR_WORLDS_CONFIG 401

#define IDC_VECTOR_WORLDS_INFO 4001
#define IDC_VECTOR_WORLDS_PRESET 4002
#define IDC_VECTOR_WORLDS_THEME 4003
#define IDC_VECTOR_WORLDS_SCENE 4004
#define IDC_VECTOR_WORLDS_SPEED 4005
#define IDC_VECTOR_WORLDS_DETAIL 4006
#define IDC_VECTOR_WORLDS_DETERMINISTIC 4007
#define IDC_VECTOR_WORLDS_DIAGNOSTICS 4008
#define IDC_VECTOR_WORLDS_DEFAULTS 4009

#endif /* VECTOR_WORLDS_RESOURCE_H */
