#ifndef CITY_NOCTURNE_RESOURCE_H
#define CITY_NOCTURNE_RESOURCE_H

#define IDD_CITY_NOCTURNE_CONFIG 1401

#define IDC_CITY_NOCTURNE_INFO 14001
#define IDC_CITY_NOCTURNE_PRESET 14002
#define IDC_CITY_NOCTURNE_THEME 14003
#define IDC_CITY_NOCTURNE_SCENE 14004
#define IDC_CITY_NOCTURNE_SPEED 14005
#define IDC_CITY_NOCTURNE_DENSITY 14006
#define IDC_CITY_NOCTURNE_DETERMINISTIC 14007
#define IDC_CITY_NOCTURNE_DIAGNOSTICS 14008
#define IDC_CITY_NOCTURNE_DEFAULTS 14009

#endif /* CITY_NOCTURNE_RESOURCE_H */
