#ifndef CITY_NOCTURNE_RESOURCE_H
#define CITY_NOCTURNE_RESOURCE_H

#define IDD_CITY_NOCTURNE_CONFIG 1701

#define IDC_CITY_NOCTURNE_INFO 17001
#define IDC_CITY_NOCTURNE_PRESET 17002
#define IDC_CITY_NOCTURNE_THEME 17003
#define IDC_CITY_NOCTURNE_SCENE 17004
#define IDC_CITY_NOCTURNE_SPEED 17005
#define IDC_CITY_NOCTURNE_DENSITY 17006
#define IDC_CITY_NOCTURNE_DETERMINISTIC 17007
#define IDC_CITY_NOCTURNE_DIAGNOSTICS 17008
#define IDC_CITY_NOCTURNE_DEFAULTS 17009

#endif /* CITY_NOCTURNE_RESOURCE_H */
