#ifndef TEMPLATE_SAVER_RESOURCE_H
#define TEMPLATE_SAVER_RESOURCE_H

#define IDD_TEMPLATE_SAVER_CONFIG 2901

#define IDC_TEMPLATE_SAVER_INFO 29001
#define IDC_TEMPLATE_SAVER_PRESET 29002
#define IDC_TEMPLATE_SAVER_THEME 29003
#define IDC_TEMPLATE_SAVER_MOTION 29004
#define IDC_TEMPLATE_SAVER_ACCENT 29005
#define IDC_TEMPLATE_SAVER_SPACING 29006
#define IDC_TEMPLATE_SAVER_DETAIL 29007
#define IDC_TEMPLATE_SAVER_DETERMINISTIC 29008
#define IDC_TEMPLATE_SAVER_DIAGNOSTICS 29009
#define IDC_TEMPLATE_SAVER_DEFAULTS 29010

#endif /* TEMPLATE_SAVER_RESOURCE_H */
