#ifndef LIFEFORMS_RESOURCE_H
#define LIFEFORMS_RESOURCE_H

#define IDD_LIFEFORMS_CONFIG 801

#define IDC_LIFEFORMS_INFO 8001
#define IDC_LIFEFORMS_PRESET 8002
#define IDC_LIFEFORMS_THEME 8003
#define IDC_LIFEFORMS_RULE 8004
#define IDC_LIFEFORMS_DENSITY 8005
#define IDC_LIFEFORMS_SEED 8006
#define IDC_LIFEFORMS_RESEED 8007
#define IDC_LIFEFORMS_DETERMINISTIC 8008
#define IDC_LIFEFORMS_DIAGNOSTICS 8009
#define IDC_LIFEFORMS_DEFAULTS 8010

#endif /* LIFEFORMS_RESOURCE_H */
