#ifndef SIGNALS_RESOURCE_H
#define SIGNALS_RESOURCE_H

#define IDD_SIGNALS_CONFIG 901

#define IDC_SIGNALS_INFO 9001
#define IDC_SIGNALS_PRESET 9002
#define IDC_SIGNALS_THEME 9003
#define IDC_SIGNALS_LAYOUT 9004
#define IDC_SIGNALS_ACTIVITY 9005
#define IDC_SIGNALS_OVERLAY 9006
#define IDC_SIGNALS_DETERMINISTIC 9007
#define IDC_SIGNALS_DIAGNOSTICS 9008
#define IDC_SIGNALS_DEFAULTS 9009

#endif /* SIGNALS_RESOURCE_H */
